# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_out', models.TimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lotdetails',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
