# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='car_make',
            new_name='carmake',
        ),
    ]
