# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20180611_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardetails',
            old_name='carmake',
            new_name='car_make',
        ),
    ]
