# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20180617_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein',
            name='time_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
