# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotOwner', '0003_lotdetails_image_of_lot'),
        ('driver', '0003_auto_20180611_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lotdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotOwner.LotDetails'),
        ),
    ]
