# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('license', models.CharField(max_length=10, null=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['join_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('national_id', models.CharField(max_length=30, null=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['join_date'],
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('national_id', models.CharField(max_length=30, null=True)),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['join_date'],
            },
        ),
    ]
