# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180609_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='phone_number',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='phone_number',
            field=models.DecimalField(decimal_places=2, max_digits=30, null=True),
        ),
    ]
