# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180611_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
