# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180611_1613'),
        ('accounts', '0004_auto_20180611_1002'),
    ]

    operations = [
    ]
