# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(default='KCA101Z', max_length=30, null=True)),
            ],
        ),
    ]
