# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotOwner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotdetails',
            old_name='Total_number_of_places',
            new_name='Total_number_of_spaces',
        ),
    ]
