# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotOwner', '0002_lotdetails_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lotdetails',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lotOwner.LotDetails'),
        ),
    ]
