# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180609_1444'),
        ('lotOwner', '0003_lotdetails_image_of_lot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Lot',
        ),
        migrations.AddField(
            model_name='location',
            name='onwer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.OwnerProfile'),
        ),
    ]
