# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotOwner', '0004_auto_20180617_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', related_query_name='location', to='lotOwner.LotDetails'),
        ),
    ]
